### ISSUE TITLE
"ENSIME Server Error: Broken pipe" at server start up

### ISSUE THREAD

**Issue by benqua** [djspiewak/ensime-sidekick#10]
Hi,

I get an "ENSIME Server Error: Broken pipe" at server start up. Works well on emacs/ENSIME.

I checked again my jEdit configuration and reread the README, but didn't find anything wrong.

ben$ cat /tmp/ensime*log
java -classpath lib/ant-1.6.5.jar:lib/wagon-http-lightweight-1.0-beta-6.jar:lib/asm-3.2.jar:lib/plexus-utils-1.5.15.jar:lib/wagon-provider-api-1.0-beta-6.jar:lib/ant-launcher-1.8.1.jar:lib/asm-tree-3.2.jar:lib/plexus-container-default-1.0-alpha-9-stable-1.jar:lib/maven-repository-metadata-2.2.1.jar:lib/asm-commons-3.2.jar:lib/plexus-interpolation-1.11.jar:lib/maven-artifact-manager-2.2.1.jar:lib/maven-error-diagnostics-2.2.1.jar:lib/critbit-0.0.4.jar:lib/nekohtml-1.9.6.2.jar:lib/maven-ant-tasks-2.1.0.jar:lib/scala-compiler.jar:lib/maven-artifact-2.2.1.jar:lib/ivy-2.1.0.jar:lib/org.eclipse.jdt.core-3.6.0.v_A58.jar:lib/classworlds-1.1-alpha-2.jar:lib/wagon-file-1.0-beta-6.jar:lib/maven-settings-2.2.1.jar:lib/ant-1.8.1.jar:lib/expectj-2.0.1.jar:lib/ensime_2.9.2-SNAPSHOT-0.7.6.RC1.jar:lib/maven-profile-2.2.1.jar:lib/org.scala-refactoring_2.9.2-0.3.0-SNAPSHOT.jar:lib/xercesMinimal-1.9.6.2.jar:lib/wagon-http-shared-1.0-beta-6.jar:lib/scala-library.jar:lib/maven-model-2.2.1.jar:lib/backport-util-concurrent-3.1.jar:lib/commons-logging-1.1.1.jar:lib/maven-plugin-registry-2.2.1.jar:lib/scalariform_2.9.1-0.1.1.jar:lib/maven-project-2.2.1.jar -XX:+DoEscapeAnalysis -Xms256M -Xmx1512M -XX:PermSize=128m -Xss1M -Dfile.encoding=UTF-8 org.ensime.server.Server /private/tmp/ensime2096556717549206314.port
Project waiting for init...
Server listening on 49477..
Wrote port 49477 to /private/tmp/ensime2096556717549206314.port.
Got connection, creating handler...

Handling RPC: (swank:init-project (:root-dir /Users/ben/Dropbox/geoscript.scala :sbt-active-subproject examples :use-sbt t :sbt-subprojects ((:name geocss :deps ()) (:name geoscript :deps (geocss)) (:name examples :deps (geoscript)))))
Using project root: /Users/ben/Dropbox/geoscript.scala
Using sbt at /Users/ben/Dropbox/Scala/ensime/dist/bin/sbt-launch-0.11.0.jar
Exception in thread "main" java.lang.NoClassDefFoundError: 
Caused by: java.lang.ClassNotFoundException: 
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
java.io.IOException: Broken pipe
    at java.io.FileOutputStream.writeBytes(Native Method)
    at java.io.FileOutputStream.write(FileOutputStream.java:282)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)
    at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:278)
    at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:122)
    at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:212)
    at java.io.BufferedWriter.flush(BufferedWriter.java:236)
    at expectj.Spawn.send(Spawn.java:403)
    at org.ensime.config.Sbt$Sbt10Style.evalUnit(Sbt.scala:271)
    at org.ensime.config.Sbt$Sbt10Style.getConfig(Sbt.scala:189)
    at org.ensime.config.Sbt$.getConfig(Sbt.scala:333)
    at org.ensime.config.ProjectConfig$$anonfun$load$1.apply(ProjectConfig.scala:197)
    at org.ensime.config.ProjectConfig$$anonfun$load$1.apply(ProjectConfig.scala:196)
    at scala.Option.foreach(Option.scala:197)
    at org.ensime.config.ProjectConfig$.load(ProjectConfig.scala:196)
    at org.ensime.config.ProjectConfig$.fromSExp(ProjectConfig.scala:172)
    at org.ensime.protocol.SwankProtocol$class.handleRPCRequest(SwankProtocol.scala:467)
    at org.ensime.protocol.SwankProtocol$class.handleEmacsRex(SwankProtocol.scala:133)
    at org.ensime.protocol.SwankProtocol$class.handleMessageForm(SwankProtocol.scala:121)
    at org.ensime.protocol.SwankProtocol$class.handleIncomingMessage(SwankProtocol.scala:113)
    at org.ensime.protocol.SwankProtocol$.handleIncomingMessage(SwankProtocol.scala:42)
    at org.ensime.server.Project$$anonfun$act$1$$anonfun$apply$mcV$sp$1.apply(Project.scala:101)
    at org.ensime.server.Project$$anonfun$act$1$$anonfun$apply$mcV$sp$1.apply(Project.scala:96)
    Writing: 000026(:return (:abort 201 "Broken pipe") 1)
at scala.actors.Actor$class.receive(Actor.scala:547)
    at org.ensime.server.Project.receive(Project.scala:77)
    at org.ensime.server.Project$$anonfun$act$1.apply$mcV$sp(Project.scala:96)
    at org.ensime.server.Project$$anonfun$act$1.apply(Project.scala:95)
    at org.ensime.server.Project$$anonfun$act$1.apply(Project.scala:95)
    at scala.actors.Reactor$class.seq(Reactor.scala:280)
    at org.ensime.server.Project.seq(Project.scala:77)
    at scala.actors.Reactor$$anon$3.andThen(Reactor.scala:258)
    at scala.actors.Combinators$class.loop(Combinators.scala:26)
    at org.ensime.server.Project.loop(Project.scala:77)
    at org.ensime.server.Project.act(Project.scala:94)
    at scala.actors.Reactor$$anonfun$dostart$1.apply(Reactor.scala:222)
    at scala.actors.Reactor$$anonfun$dostart$1.apply(Reactor.scala:222)
    at scala.actors.ReactorTask.run(ReactorTask.scala:33)
    at scala.concurrent.forkjoin.ForkJoinPool$AdaptedRunnable.exec(ForkJoinPool.java:611)
    at scala.concurrent.forkjoin.ForkJoinTask.quietlyExec(ForkJoinTask.java:422)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.mainLoop(ForkJoinWorkerThread.java:340)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:325)

I think it can be reproduce with the project  https://github.com/dwins/geoscript.scala and a .ensime file like:
(
:use-sbt t
:sbt-subprojects (
     (:name "geocss" :deps ())
     (:name "geoscript" :deps ("geocss"))
     (:name "examples" :deps ("geoscript"))
  )
)

**Comment by djspiewak** [comment]
Hmm, my coworker has been seeing this as well.  I have generally been unable to reproduce it though.  Really glad to hear there's a consistent way to dup the problem!  I'll look into it in the next few days.

**Comment by aemoncannon** [comment]
If I'm reading this correctly, it seems the broken pipe is a result of the inferior sbt process dying before the bytes can be written to its stdin. I guess it's dying due to that classnotfoundexception. 

I have two suggestions:
1) Try using a directory, rather than a scala file, for the :root-dir. This should be a directory, and I'm not confident how ensime will behave if it's a file.
2) Grab the latest RC from ensime downloads. At the very least, it does a better job of printing the full sbt launch commandline, so it'll be easier to try to reproduce the sbt crash.

**Comment by aemoncannon** [comment]
Btw, 
Declaring sbt dependencies in .ensime is no longer necessary. Still need the :name though. (see ENSIME manual, recent update)

**Comment by djspiewak** [comment]
re 1) That actually _is_ the directory, not the Scala file.  It's a little weird that way.  :-)  My coworker is able to dup this (100% of the time) with Anti-XML.

**Comment by benqua** [comment]
I tried with the latest trunk version of ensime with the exact same result.

**Comment by djspiewak** [comment]
Can you post your ensime log from the latest trunk version?  The idea is to see the exact invocation used for SBT.

**Comment by benqua** [comment]
sure. (ensime trunk and your latest jar for the jedit plugin)

ben$ cat /tmp/ensime*log
java -classpath lib/ant-1.6.5.jar:lib/wagon-http-lightweight-1.0-beta-6.jar:lib/asm-3.2.jar:lib/plexus-utils-1.5.15.jar:lib/wagon-provider-api-1.0-beta-6.jar:lib/ant-launcher-1.8.1.jar:lib/asm-tree-3.2.jar:lib/plexus-container-default-1.0-alpha-9-stable-1.jar:lib/maven-repository-metadata-2.2.1.jar:lib/asm-commons-3.2.jar:lib/plexus-interpolation-1.11.jar:lib/maven-artifact-manager-2.2.1.jar:lib/maven-error-diagnostics-2.2.1.jar:lib/critbit-0.0.4.jar:lib/nekohtml-1.9.6.2.jar:lib/maven-ant-tasks-2.1.0.jar:lib/scala-compiler.jar:lib/maven-artifact-2.2.1.jar:lib/ivy-2.1.0.jar:lib/org.eclipse.jdt.core-3.6.0.v_A58.jar:lib/classworlds-1.1-alpha-2.jar:lib/wagon-file-1.0-beta-6.jar:lib/maven-settings-2.2.1.jar:lib/ant-1.8.1.jar:lib/expectj-2.0.1.jar:lib/ensime_2.9.2-SNAPSHOT-0.7.6.RC1.jar:lib/maven-profile-2.2.1.jar:lib/org.scala-refactoring_2.9.2-0.3.0-SNAPSHOT.jar:lib/xercesMinimal-1.9.6.2.jar:lib/wagon-http-shared-1.0-beta-6.jar:lib/scala-library.jar:lib/maven-model-2.2.1.jar:lib/backport-util-concurrent-3.1.jar:lib/commons-logging-1.1.1.jar:lib/maven-plugin-registry-2.2.1.jar:lib/scalariform_2.9.1-0.1.1.jar:lib/maven-project-2.2.1.jar -XX:+DoEscapeAnalysis -Xms256M -Xmx1512M -XX:PermSize=128m -Xss1M -Dfile.encoding=UTF-8 org.ensime.server.Server /private/tmp/ensime3738234846275593546.port
Project waiting for init...
Server listening on 49860..
Wrote port 49860 to /private/tmp/ensime3738234846275593546.port.
Got connection, creating handler...

Handling RPC: (swank:init-project (:root-dir /Users/ben/Dropbox/geoscript.scala :sbt-active-subproject examples :use-sbt t :sbt-subprojects ((:name geocss :deps ()) (:name geoscript :deps (geocss)) (:name examples :deps (geoscript)))))
Using project root: /Users/ben/Dropbox/geoscript.scala
Using sbt at /Users/ben/Dropbox/Scala/ensime/dist/bin/sbt-launch-0.11.0.jar
Exception in thread "main" java.lang.NoClassDefFoundError: 
Caused by: java.lang.ClassNotFoundException: 
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
java.io.IOException: Broken pipe
    at java.io.FileOutputStream.wririeing: 000026(:return (:ab rt 201 "Broken pipe") 1)
java.io.FileOutputStream.write(FileOutputStream.java:282)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)
    at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:278)
    at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:122)
    at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:212)
    at java.io.BufferedWriter.flush(BufferedWriter.java:236)
    at expectj.Spawn.send(Spawn.java:403)
    at org.ensime.config.Sbt$Sbt10Style.evalUnit(Sbt.scala:271)
    at org.ensime.config.Sbt$Sbt10Style.getConfig(Sbt.scala:189)
    at org.ensime.config.Sbt$.getConfig(Sbt.scala:333)
    at org.ensime.config.ProjectConfig$$anonfun$load$1.apply(ProjectConfig.scala:197)
    at org.ensime.config.ProjectConfig$$anonfun$load$1.apply(ProjectConfig.scala:196)
    at scala.Option.foreach(Option.scala:197)
    at org.ensime.config.ProjectConfig$.load(ProjectConfig.scala:196)
    at org.ensime.config.ProjectConfig$.fromSExp(ProjectConfig.scala:172)
    at org.ensime.protocol.SwankProtocol$class.handleRPCRequest(SwankProtocol.scala:467)
    at org.ensime.protocol.SwankProtocol$class.handleEmacsRex(SwankProtocol.scala:133)
    at org.ensime.protocol.SwankProtocol$class.handleMessageForm(SwankProtocol.scala:121)
    at org.ensime.protocol.SwankProtocol$class.handleIncomingMessage(SwankProtocol.scala:113)
    at org.ensime.protocol.SwankProtocol$.handleIncomingMessage(SwankProtocol.scala:42)
    at org.ensime.server.Project$$anonfun$act$1$$anonfun$apply$mcV$sp$1.apply(Project.scala:101)
    at org.ensime.server.Project$$anonfun$act$1$$anonfun$apply$mcV$sp$1.apply(Project.scala:96)
    at scala.actors.Actor$class.receive(Actor.scala:547)
    at org.ensime.server.Project.receive(Project.scala:77)
    at org.ensime.server.Project$$anonfun$act$1.apply$mcV$sp(Project.scala:96)
    at org.ensime.server.Project$$anonfun$act$1.apply(Project.scala:95)
    at org.ensime.server.Project$$anonfun$act$1.apply(Project.scala:95)
    at scala.actors.Reactor$class.seq(Reactor.scala:280)
    at org.ensime.server.Project.seq(Project.scala:77)
    at scala.actors.Reactor$$anon$3.andThen(Reactor.scala:258)
    at scala.actors.Combinators$class.loop(Combinators.scala:26)
    at org.ensime.server.Project.loop(Project.scala:77)
    at org.ensime.server.Project.act(Project.scala:94)
    at scala.actors.Reactor$$anonfun$dostart$1.apply(Reactor.scala:222)
    at scala.actors.Reactor$$anonfun$dostart$1.apply(Reactor.scala:222)
    at scala.actors.ReactorTask.run(ReactorTask.scala:33)
    at scala.concurrent.forkjoin.ForkJoinPool$AdaptedRunnable.exec(ForkJoinPool.java:611)
    at scala.concurrent.forkjoin.ForkJoinTask.quietlyExec(ForkJoinTask.java:422)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.mainLoop(ForkJoinWorkerThread.java:340)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:325)

**Comment by djspiewak** [comment]
It really looks like what's happening is SBT's main class is failing to load.  Can you try running `java -jar /Users/ben/Dropbox/Scala/ensime/dist/bin/sbt-launch-0.11.0.jar` in your project root to see if it works?  I can't imagine you ended up with a corrupt JAR, but just in case…

**Comment by benqua** [comment]
ben$ java -jar /Users/ben/Dropbox/Scala/ensime/dist/bin/sbt-launch-0.11.0.jar
[info] Loading project definition from /Users/ben/Dropbox/geoscript.scala/project
[info] Updating {file:/Users/ben/Dropbox/geoscript.scala/project/}default-afacb1...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/ben/Dropbox/geoscript.scala/project/target/scala-2.9.1/sbt-0.11.0/classes...
[warn] there were 3 deprecation warnings; re-run with -deprecation for details
[warn] one warning found
[info] Set current project to root (in build file:/Users/ben/Dropbox/geoscript.scala/)

**Comment by benqua** [comment]
Btw it works on emacs. But I am not sure if emacs use the same copy of sbt-launch. my .emacs adds some paths:

(add-to-list 'load-path "~/Dropbox/Scala/ensime/dist/elisp/")
(require 'ensime)
(add-hook 'scala-mode-hook 'ensime-scala-mode-hook)

(push "~/Dropbox/Scala/ensime/dist/" exec-path)
(push "/usr/local/scala/bin/" exec-path)
(push "~/bin/" exec-path)

**Comment by benqua** [comment]
sorry, didn't want to close it.

**Comment by aemoncannon** [comment]
Hey Benqua, 
Could you install ENSIME 0.8.0 RC2 from https://github.com/aemoncannon/ensime/downloads
and paste us the log output? For whatever reason the log above is from an older version.

My guess is there's something funny about the sbt command-line.

**Comment by benqua** [comment]
yes, my bad, the jEdit dialog box to select the ensime path behave strangely.

Here's what I get:

$ cat /tmp/ensime*log
java -classpath lib/maven-artifact-manager-2.2.1.jar:lib/nekohtml-1.9.6.2.jar:lib/xercesMinimal-1.9.6.2.jar:lib/plexus-utils-1.5.15.jar:lib/maven-settings-2.2.1.jar:lib/wagon-file-1.0-beta-6.jar:lib/classworlds-1.1-alpha-2.jar:lib/commons-logging-1.1.1.jar:lib/asm-commons-3.2.jar:lib/scalariform_2.9.1-0.1.1.jar:lib/ant-1.6.5.jar:lib/critbit-0.0.4.jar:lib/ant-launcher-1.8.1.jar:lib/scala-compiler.jar:lib/ensime_2.9.2-SNAPSHOT-0.8.0.RC2.jar:lib/wagon-http-shared-1.0-beta-6.jar:lib/maven-ant-tasks-2.1.0.jar:lib/wagon-http-lightweight-1.0-beta-6.jar:lib/maven-project-2.2.1.jar:lib/maven-model-2.2.1.jar:lib/org.scala-refactoring_2.9.2-SNAPSHOT-0.3.0-SNAPSHOT.jar:lib/ant-1.8.1.jar:lib/backport-util-concurrent-3.1.jar:lib/maven-profile-2.2.1.jar:lib/scala-library.jar:lib/maven-repository-metadata-2.2.1.jar:lib/maven-plugin-registry-2.2.1.jar:lib/expectj-2.0.1.jar:lib/plexus-interpolation-1.11.jar:lib/plexus-container-default-1.0-alpha-9-stable-1.jar:lib/maven-artifact-2.2.1.jar:lib/ivy-2.1.0.jar:lib/wagon-provider-api-1.0-beta-6.jar:lib/asm-tree-3.2.jar:lib/asm-3.2.jar:lib/maven-error-diagnostics-2.2.1.jar:lib/org.eclipse.jdt.core-3.6.0.v_A58.jar -XX:+DoEscapeAnalysis -Xms256M -Xmx1512M -XX:PermSize=128m -Xss1M -Dfile.encoding=UTF-8 org.ensime.server.Server /private/tmp/ensime7903802533158803926.port
Project waiting for init...
Server listening on 49296..
Wrote port 49296 to /private/tmp/ensime7903802533158803926.port.
Got connection, creating handler...

Handling RPC: (swank:init-project (:root-dir /Users/ben/Dropbox/geoscript.scala :sbt-active-subproject examples :use-sbt t :sbt-subprojects ((:name geocss :deps ()) (:name geoscript :deps (geocss)) (:name examples :deps (geoscript)))))
Using project root: /Users/ben/Dropbox/geoscript.scala
Starting sbt with command line: java -Xmx512M  -Djline.terminal=jline.UnixTerminal -Dsbt.log.noformat=true -jar /Users/ben/Dropbox/Scala/ensime_2.9.2-SNAPSHOT-0.8.0.RC2/bin/sbt-launch-0.11.0.jar
Exception in thread "main" java.lang.NoClassDefFoundError: 
Caused by: java.lang.ClassNotFoundException: 
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
java.io.IOException: Broken pipe
    at java.io.FileOutputStream.writeBytes(Native Method)
    at java.io.FileOutputStream.write(FileOutputStream.java:282)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)
    at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:278)
    at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:122)
    at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:212)
    at java.io.BufferedWriter.flush(BufferedWriter.java:236)
    at expectj.Spawn.send(Spawn.java:403)
    at org.ensime.config.Sbt$Sbt10Style.evalUnit(Sbt.scala:281)
    at org.ensime.config.Sbt$Sbt10Style.getConfig(Sbt.scala:208)
    at org.ensime.config.Sbt$.getConfig(Sbt.scala:343)
    at org.ensime.config.ProjectConfig$$anonfun$load$1.apply(ProjectConfig.scala:197)
    at org.ensime.config.ProjectConfig$$anonfun$load$1.apply(ProjectConfig.scala:196)
    at scala.Option.foreach(Option.scala:197)
    at org.ensime.config.ProjectConfig$.load(ProjectConfig.scala:196)
    at org.ensime.config.ProjectConfig$.fromSExp(ProjectConfig.scala:172)
    at org.ensime.protocol.SwankProtocol$class.handleRPCRequest(SwankProtocol.scala:467)
    at org.ensime.protocol.SwankProtocol$class.handleEmacsRex(SwankProtocol.scala:133)
    at org.ensime.protocol.SwankProtocol$class.handleMessageForm(SwankProtocol.scala:121)
    at org.ensime.protocol.SwankProtocol$claWriting: 000026(:return (:abort 201 "Broken pipe") 1)
ss.handleIncomingMessage(SwankProtocol.scala:113)
    at org.ensime.protocol.SwankProtocol$.handleIncomingMessage(SwankProtocol.scala:42)
    at org.ensime.server.Project$$anonfun$act$1$$anonfun$apply$mcV$sp$1.apply(Project.scala:101)
    at org.ensime.server.Project$$anonfun$act$1$$anonfun$apply$mcV$sp$1.apply(Project.scala:96)
    at scala.actors.Actor$class.receive(Actor.scala:547)
    at org.ensime.server.Project.receive(Project.scala:77)
    at org.ensime.server.Project$$anonfun$act$1.apply$mcV$sp(Project.scala:96)
    at org.ensime.server.Project$$anonfun$act$1.apply(Project.scala:95)
    at org.ensime.server.Project$$anonfun$act$1.apply(Project.scala:95)
    at scala.actors.Reactor$class.seq(Reactor.scala:280)
    at org.ensime.server.Project.seq(Project.scala:77)
    at scala.actors.Reactor$$anon$3.andThen(Reactor.scala:258)
    at scala.actors.Combinators$class.loop(Combinators.scala:26)
    at org.ensime.server.Project.loop(Project.scala:77)
    at org.ensime.server.Project.act(Project.scala:94)
    at scala.actors.Reactor$$anonfun$dostart$1.apply(Reactor.scala:222)
    at scala.actors.Reactor$$anonfun$dostart$1.apply(Reactor.scala:222)
    at scala.actors.ReactorTask.run(ReactorTask.scala:33)
    at scala.concurrent.forkjoin.ForkJoinPool$AdaptedRunnable.exec(ForkJoinPool.java:611)
    at scala.concurrent.forkjoin.ForkJoinTask.quietlyExec(ForkJoinTask.java:422)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.mainLoop(ForkJoinWorkerThread.java:340)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:325)

The strange thing is that it works from a terminal:
$ cd /Users/ben/Dropbox/geoscript.scala
$ java -Xmx512M  -Djline.terminal=jline.UnixTerminal -Dsbt.log.noformat=true -jar /Users/ben/Dropbox/Scala/ensime_2.9.2-SNAPSHOT-0.8.0.RC2/bin/sbt-launch-0.11.0.jar
[info] Loading project definition from /Users/ben/Dropbox/geoscript.scala/project
[info] Set current project to root (in build file:/Users/ben/Dropbox/geoscript.scala/)


And it also works from emacs (btw is there an ensime server log when running from emacs?)

How is it possible the the above command doesn't work when run from ensime-jedit but works when run by hand in a terminal or from ensime-emacs? some environnement variables / classpath issue? Seems strange because the path is absolute and I don't see what the classpath would change.

**Comment by aemoncannon** [comment]
Hmm. Mysterious.
Maybe something to do with the permissions granted to ENSIME process on start... but i don't see why that would be different on your system. Have you tried creating a fresh project that's _not_ under the Dropbox folder? I wonder if that could be messing with things.

At this point it might help to run jedit under strace (dftrace i think on mac..) with the -f option to also trace forked subprocesses. The idea being to find the system call (probably trying to access a file) that is causing the exception.

**Comment by benqua** [comment]
ok, I think I got it.

Investigating with dtruss (strace), I realized the java process was launched without the jar argument, just after the message:
Starting sbt with command line: java -Xmx512M  -Djline.terminal=jline.UnixTerminal -Dsbt.log.noformat=true -jar /Users/ben/Downloads/ensime_2.9.2-SNAPSHOT-0.8.0.RC2/bin/sbt-launch-0.11.0.jar

I also noticed the double space between "-Xmx512M" and "-Djline.terminal=jline.UnixTerminal".

In /ensime/src/main/scala/org/ensime/config/Sbt.scala, line 65:

```
def jvmArgs:Seq[String] = List("-Xmx512M") ++ (
  Option(System getenv "SBT_OPTS") map { _ split "\\s+" } map { arr => Vector(arr: _*) } getOrElse Vector())
```

It seems the ProcessBuilder doesn't like the element added to List(("-Xmx512M")
If I comment the second line (and the "++ (" ), it works.

For some reason, my SBT_OPTS is probably different in emacs.

**Comment by aemoncannon** [comment]
Nice!
I still don't understand exactly what's breaking, though... Is there a special character in your SBT_OPTS or something?

**Comment by djspiewak** [comment]
In the category of wild-and-crazy theories, what happens if you change `List("-Xmx512M") ++ (` to simply `"-Xmx512M" +: (`?

To the best of my knowledge, Emacs doesn't pass `SBT_OPTS` at all.  jEdit, on the other hand, passes it every time.  By default, it is set to the empty string.  It almost looks like `ProcessBuilder` is getting `" "` for that argument and then passing it along to SBT, which fails in parsing that arg and thus crashes.  There appear to be three problems here:
- Either ENSIME or jEdit is somehow getting `jvmArgs` to contain `Seq("-Xmx512M", " ")`
- SBT's argument parsing doesn't handle the empty string (probably because it never arises when launched from a shell)
- ENSIME doesn't have particularly elegant handling for when SBT crashes unexpectedly

I would say the second bug is the most serious one, and we should probably open it against the harrah/xsbt project if we can turn it into a minimal case.  The first bug is of course the root of all our troubles, and it's certainly the most mysterious.  As for the third bug, let's just call that a "nice to have".  :-)

**Comment by aemoncannon** [comment]
Just pushed an ENSIME commit that handles 1 by filtering out whitespace
args, and is a bit more friendly in the face of 2.

On Tue, Nov 15, 2011 at 7:18 PM, Daniel Spiewak <
reply@reply.github.com

**Comment by benqua** [comment]
sbt argument parsing is not to blame in this case. From what I see in dtruss, java is called without argument. The java process looks for .class files in the current directory. So, sbt is not even called.

The ProcessBuilder behave strangely when he gets an empty string in its argument list. It seems he just ignore all arguments following the empty string.

BTW, is it the right way to pass option to sbt?
If I read it well, we would get something like:
java -Xmx512M SBTOPTIONS -Djline.terminal=jline.UnixTerminal -Dsbt.log.noformat=true -jar /Users/ben/Downloads/ensime_2.9.2-SNAPSHOT-0.8.0.RC2/bin/sbt-launch-0.11.0.jar
when I would expect
java -Xmx512M -Djline.terminal=jline.UnixTerminal -Dsbt.log.noformat=true -jar /Users/ben/Downloads/ensime_2.9.2-SNAPSHOT-0.8.0.RC2/bin/sbt-launch-0.11.0.jar SBTOPTIONS

But I am not really expert in the java command line...

Anyhow, I think it is more related to ensime itself than to the the jedit-plugin (which I will hopefully be able to try tonight after spending quite some time on this well hidden issue!).

Thanks for your hints, I wouldn't have find it without them.

**Comment by benqua** [comment]
It works with the latest version of ensime.  Thanks!
